# see 
# * https://docs.searxng.org/admin/settings/settings.html#use-default-settings
# * full settings.yml: https://github.com/searxng/searxng/blob/master/searx/settings.yml
use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b' # Is overwritten by ${SEARXNG_SECRET}
